meta:
  engine: 4.0.4
  name: example
  version: 0.1
  # ref: &kb_ref "Example v0.1"
  # author: &kb_author Example
  # url: &kb_url https://github.com/username/example-ergogen

  fp_key_switch: &fp_key_switch "ceoloide/switch_choc_v1_v2"
  fp_reset_switch: &fp_reset_switch "ceoloide/reset_switch_smd_side"
  fp_power_switch: &fp_power_switch "ceoloide/power_switch_smd_side"
  fp_mounting_hole: &fp_mounting_hole "ceoloide/mounting_hole"
  fp_mcu: &fp_mcu "ceoloide/nice_nano"
  fp_oled: &fp_oled "ceoloide/display_ssd1306_nice_view"
  fp_battery_connector: &fp_fp_battery_connector "ceoloide/battery_connector_jst_ph_2"
  fp_diode: &fp_diode "ceoloide/diode_tht_sod123"

  switch:
    $extends: presets.choc_v1

presets:
  # Original presets by Ceoloide https://github.com/ceoloide/corney-island
  # These presets provide different layout options
  # Select a preset in the `units` section below
  # Note: The appropriate switch footprint will still need to be set in the `pcb` section
  mx:
    # Key and keycap measures
    kx: u # spacing between key centers (X-axis)
    ky: u # spacing between key centers (Y-axis)
    kcow: 14 # key cutout hole width (cherry: 14, choc: 13.8)
    kcoh: 14 # key cutout hole height (cherry: 14, choc: 13.8)
    keycw: 18 # keycap width (cherry: 18, choc: 17.5, choc CFX 16.5)
    keych: 18 # keycap height (cherry: 18, choc: 16.5, choc CFX 16.5)
    led_pos_x: 0 # Led X position relative to the switch center
    led_pos_y: -4.75 # Led Y position relative to the switch center
    led_rotation: 180 # Led rotation
    vertical_underglow_shift: -0.5 kp # How much to shift underglow leds tied to keys
    vertical_diode_shift: 1.325 # How much to shift to avoid overlap
    horizontal_diode_shift: 7.4
    diode_rotation: 0 # Diode rotation
    switch_rotation: 0 # Hotswap north, led south
    # Switch specific case variables
    top_plate_thickness: 1.6
    internal_distance_to_top_plate: 5

  choc_v1:
    # Key and keycap measures
    u: 17
    U: 17
    kx: 17 # spacing between key centers (X-axis)
    ky: 17 # spacing between key centers (Y-axis)
    kcow: 13.8 # key cutout hole width (cherry, choc v2: 14, choc v1: 13.8)
    kcoh: 13.8 # key cutout hole height (cherry, choc v2: 14, choc v1: 13.8)
    kcw: 16.5 # keycap width (cherry: 18, choc: 17.5, choc CFX 16.5)
    kch: 16.5 # keycap height (cherry: 18, choc: 16.5, choc CFX 16.5)
    tkch: 1.25kch # thumb keycap height
    led_pos_x: 0 # Led X position relative to the switch center
    led_pos_y: 4.7 # Led Y position relative to the switch center
    led_rotation: 0 # Led rotation
    vertical_underglow_shift: -kx + 7.8 # How much to shift underglow leds tied to keys
    vertical_diode_shift: 1.5 # How much to shift to avoid overlap
    horizontal_diode_shift: -0.5 kcow - 0.85
    diode_rotation: 0 # Diode rotation
    switch_rotation: 180 # Hotswap south, led north
    # Switch specific case variables
    top_plate_thickness: 1.3
    internal_distance_to_top_plate: 2.2
units:
  # The following statements will make the content of the preset
  # available in the units context
  $extends: meta.switch
  $default_autobind: 0

  # Physical measures
  screw_radius: 1.1 # M2 screws
  screw_diameter: screw_radius * 2
  screw_head_radius: 2.05
  screw_head_diameter: screw_head_radius * 2
  standoff_radius: 1.575 + 0.125 # M2 standoffs https://keeb.io/products/m2-screws-and-standoffs
  standoff_diameter: standoff_radius * 2 # 3.15 + 0.25 for tolerances
  fillet_radius: 0.5
  pwr_trace_width: 0.25
  gnd_trace_width: 0.25
  signal_trace_width: 0.15
  via_size: 0.56 # JLCPCB min 0.56 | KiCad default 0.8
  via_drill: 0.3 # JLCPCB min 0.3 | KiCad default 0.4

  case_wall_thickness: 0.5
  pcb_to_case_wall_tolerance: 0.25
  bottom_plate_thickness: 1.0
  internal_distance_to_bottom_plate: 4

  mcu_margin_right: 0.5
  mcu_margin_top: 0.55kx

points:
  zones:
    main:
      anchor.shift: [100, -100] # Fix KiCad placement
      key.tags: [main_key, key]
      columns:
        inner.key:
          tags: [key_1u]
        index.key:
          tags: [key_1u]
          column_net: C4
        middle.key:
          tags: [key_1u]
          column_net: C3
        ring.key:
          tags: [key_1u]
          column_net: C2
        pinky:
          key:
            tags: [key_1u]
            column_net: C1
        outer:
          key:
            tags: [key_1_25u]
            column_net: C0
            stagger: 0.5ky
            padding: 1.25ky
          rows:
            top.skip: true
      rows:
        bottom:
          row_net: R1
        home:
          row_net: R2
        top:
          row_net: R3

    thumb:
      anchor:
        ref: main_inner_bottom
        shift: [-1.3kx, -1.8ky]
        rotate: 12
      key:
        tags: [key, thumb_key, key_1_25u]
        origin: [-0.5kx, -0.5ky]

      columns:
        outer.key:
        middle.key:
          stagger: 3
          splay: -3
        inner.key:
          stagger: 6
          splay: -12
          shift: [0.5, -2]
      rows.home:
        row_net: R0

    # helper points
    svg_viewport_fix1:
      key.tags: [viewport_fix]
      anchor:
        ref: main_inner_top
        shift: [-45, 30]

    svg_viewport_fix2:
      key.tags: [viewport_fix]
      anchor:
        ref: main_inner_bottom
        shift: [-45, -55]

    mcu_top_right:
      key.tags: [helper]
      anchor:
        ref: main_inner_top
        shift: [-0.5kx - mcu_margin_right, 0.5ky - mcu_margin_top]

    mcu_top_left:
      key.tags: [helper]
      anchor:
        ref: mcu_top_right
        shift: [-18, 0]

    mcu_bottom_right:
      key.tags: [helper]
      anchor:
        ref: mcu_top_right
        shift: [0, -33.4]
    mcu_bottom_left:
      key.tags: [helper]
      anchor:
        ref: mcu_top_left
        shift: [0, -33.4]

    mcu_center:
      key.tags: [helper]
      anchor:
        aggregate:
          parts:
            - ref: mcu_bottom_left
            - ref: mcu_top_left
            - ref: mcu_top_right
            - ref: mcu_bottom_right

    screw_right_top:
      key.tags: [helper, screw, standoff]
      anchor:
        - aggregate:
            parts:
              - ref: main_pinky_top
              - ref: main_outer_top
              - ref: main_pinky_home
              - ref: main_outer_home

    screw_right_bottom:
      key.tags: [helper, screw, standoff]
      anchor:
        - aggregate:
            parts:
              - ref: main_pinky_home
              - ref: main_outer_home
              - ref: main_pinky_bottom
              - ref: main_outer_bottom

    screw_mcu_top_right:
      key.tags: [helper, screw]
      anchor:
        - ref: mcu_top_right
          shift: [-2, 2.4]

    screw_mcu_top_left:
      key.tags: [helper, screw]
      anchor:
        - ref: mcu_top_left
          shift: [2, 2.4]

    tp_center:
      key.tags: [helper]
      anchor:
        aggregate:
          parts:
            - ref: main_middle_top
            - ref: main_ring_top
            - ref: main_middle_home
            - ref: main_ring_home
        shift: [0, 0]
        rotate: 0

    screw_tp_top:
      key.tags: [helper, screw]
      anchor:
        ref: tp_center
        shift: [0, 19.05]

    screw_tp_bottom:
      key.tags: [helper, screw]
      anchor:
        ref: tp_center
        shift: [0, -19.05]

    screw_tp_left:
      key.tags: [helper, screw]
      anchor:
        ref: tp_center
        shift: [-19.05, 0]

    screw_tp_right:
      key.tags: [helper, screw]
      anchor:
        ref: tp_center
        shift: [19.05, 0]

outlines:
  _viewport_fix:
    - what: rectangle
      where: [viewport_fix]
      size: 5

  _grid:
    - what: rectangle
      where: [key_1u]
      size: [kx, ky]
      operation: stack
    - what: rectangle
      where: [key_1_25u]
      size: [kx, 1.25ky]
      operation: stack
    - what: rectangle
      where: [key_1_5u]
      size: [kx, 1.5ky]
      operation: stack

  _keycaps:
    # center dot
    - what: circle
      where: [key]
      radius: 0.25
      # 1u
    - what: rectangle
      where: [key_1u]
      operation: stack
      size: [kch, kcw]
      corner: 1.5
    - what: rectangle
      where: [key_1u]
      size: [kch - 2.5, kcw - 2.5]
      corner: 1
      operation: stack
      # 1.25u
    - what: rectangle
      where: [key_1_25u]
      operation: stack
      size: [kch, 1.25kcw]
      corner: 1.5
    - what: rectangle
      where: [key_1_25u]
      size: [kch - 2.5, 1.25kcw - 2.5]
      corner: 1
      operation: stack
      # 1.5u
    - what: rectangle
      where: [key_1_5u]
      operation: stack
      size: [kch, 1.5kcw]
      corner: 1.5
    - what: rectangle
      where: [key_1_5u]
      size: [kch - 2.5, 1.5kcw - 2.5]
      corner: 1
      operation: stack

  _screws:
    - what: circle
      where: [screw]
      radius: screw_radius

  _screwheads:
    - what: circle
      where: [screw]
      radius: screw_head_radius
      operation: stack

  _standoffs:
    - what: circle
      where: [standoff]
      radius: standoff_radius
      operation: stack

  _switches:
    - what: rectangle
      where: [key]
      size: [kcow, kcoh]

  _tentingpuck:
    - what: circle
      where: tp_center
      radius: 20.55

  _mcu_raw:
    - what: rectangle
      where: mcu_center
      size: [18, 33.4]

  _mcu:
    - what: outline
      name: _mcu_raw
      fillet: 1.75

  _debug_points:
    - what: rectangle
      where: true
      size: [3, 0.01]
      adjust:
        rotate: 45
    - what: rectangle
      where: true
      size: [0.01, 3]
      adjust:
        rotate: 45
      operation: stack
    - what: circle
      where: true
      radius: 0.4
      adjust:
        shift: [1.15, 1.15]

  debug_preview:
    - ^_viewport_fix
    - ^_grid
    - ^_debug_points
    - ^_screws
    - ^_switches
    - ^_standoffs
    - ^_mcu
    - ^_tentingpuck

  preview:
    - ^_viewport_fix
    - ^_keycaps
    - ^_mcu
